import "./verify";
import "./debug";
import "./event";
import "./team";
import "./probate";
import "./leaderboard";
import "./predict";
import "./role";
import "./help";
import "./dumb";
import "./voicetrack"
import "./purge";
import "./control";